### PR TITLE
Fix port number in URL

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by mraible** [comment]
Even after fixing this, I don't see the OpenFGA model in the playground. I did run the following and it looked like it succeeded:

```
cd openfga
./import.sh
```

**Comment by embesozzi** [comment]
It's strange, I've imported the schema several times without any problems. You should see something similar:

```sh
% ./import.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- 100   168  100   142  100    26   9466   1733 --:--:-- --:--:-- --:--:-- 11200
OpenFGA store id:  + 01HEE8BEG7PPVJM65D8JT9D71R
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- 100  2018  100    55  100  1963   3666   127k --:--:-- --:--:-- --:--:--  131k
OpenFGA authorization model id:  + 01HEE8BEGZ4ZNWA5CJSGCACJJT
```

In the openfga container logs, you will see something like this:

```
openfga            | 2023-11-04T23:02:04.067Z   INFO    grpc_req_complete       {"grpc_service": "openfga.v1.OpenFGAService", "grpc_method": "CreateStore", "grpc_type": "unary", "request_id": "445adb29-c3fc-434a-bc35-1a9e69e62556", "user_agent": "curl/7.64.1", "raw_request": {"name":"keycloak"}, "raw_response": {"id":"01HEE8BEG7PPVJM65D8JT9D71R","name":"keycloak","created_at":"2023-11-04T23:02:04.063319Z","updated_at":"2023-11-04T23:02:04.063319Z"}, "peer.address": "127.0.0.1:33174", "grpc_code": 0}
openfga            | 2023-11-04T23:02:04.085Z   INFO    grpc_req_complete       {"grpc_service": "openfga.v1.OpenFGAService", "grpc_method": "WriteAuthorizationModel", "grpc_type": "unary", "request_id": "0ebb45a2-df71-44de-8984-940320aec63d", "user_agent": "curl/7.64.1", "raw_request": {"store_id":"01HEE94VGVM32BR60CQJKQNFBH","type_definitions":[{"type":"group","relations":{"assignee":{"this":{}}},"metadata":{"relations":{"assignee":{"directly_related_user_types":[{"type":"user"}]}}}},{"type":"role","relations":{"assignee":{"union":{"child":[{"this":{}},{"tupleToUserset":{"tupleset":{"object":"","relation":"parent"},"computedUserset":{"object":"","relation":"assignee"}}},{"tupleToUserset":{"tupleset":{"object":"","relation":"parent_group"},"computedUserset":{"object":"","relation":"assignee"}}}]}},"parent":{"this":{}},"parent_group":{"this":{}}},"metadata":{"relations":{"assignee":{"directly_related_user_types":[{"type":"user"}]},"parent":{"directly_related_user_types":[{"type":"role"}]},"parent_group":{"directly_related_user_types":[{"type":"group"}]}}}},{"type":"user","relations":{},"metadata":null}],"schema_version":"1.1"}, "raw_response": {"authorization_model_id":"01HEE8BEGZ4ZNWA5CJSGCACJJT"}, "peer.address": "127.0.0.1:33174", "store_id": "01HEE8BEG7PPVJM65D8JT9D71R", "grpc_code": 0}

```


You also have the option to create it manually through the playground console using the following [DSL model](https://github.com/embesozzi/keycloak-openfga-event-publisher/blob/main/model.dsl).

**Comment by embesozzi** [comment]
I've just added the latest release of a new docker compose file, called [docker-compose-import.yml](https://github.com/embesozzi/keycloak-openfga-workshop/blob/main/docker-compose-import.yml ) for automatically importing all the required configurations into the Keycloak and OpenFGA platforms. Therefore, no manual steps are needed.

**Comment by mraible** [comment]
Hello, @embesozzi! I can confirm that everything works now. Thank you for your efforts!

One thing I noticed is the Keycloak image is now `quay.io/keycloak/keycloak:21.1`. You might want to update the README because it has `quay.io/keycloak/keycloak:19.0.2`.

**Pull request closed without merging**
